### ISSUE TITLE
The Complex Filter only synchronize all levels the first time

### ISSUE THREAD

**Issue by ricardoamm** [Mimetis/Dotmim.Sync#807]
I have a complex filter with 4 levels, in the first time all the databases tables are aprovisioned and synchronized.
In the following synchronizations, I edit another server level 0 table to match the filter, but only the level 0 table are synchronized.

**Comment by Mimetis** [comment]
I need a sample to understand (and the version you are using)

**Comment by ricardoamm** [comment]
Hello,

Thanks for your quick reply.
I'm using the version 0.9.5.
In attachment follows my SyncSetup.

Best Regards,
Ricardo

[ErpDatabase.cs.txt](https://github.com/Mimetis/Dotmim.Sync/files/9508083/ErpDatabase.cs.txt)

**Comment by Mimetis** [comment]
Will be complicated for me without a database sample script. Do you have a simple script to create the tables you have ? (with sample rows) 
Can you try with the last beta version 0.9.6 ?
This pre release version is adding a better support for filters.

**Comment by ricardoamm** [comment]
I tried the beta version 0.9.6, but the behaviour remains.
It's hard to me send the ERP database, but i reproduced the problem with the AdventureWorks database and the Complex Filter Sample found on the Git Repo.
If I change the SyncParameters for the second time with valid City and postalcode, no data is downloaded.

**Comment by Mimetis** [comment]
Ok, if you can reproduce it with `AdventureWorks`, it will be easier to understand what the problem is.
I tried your scenario, and it seems to work for me at least:

``` cs
var parameters = new SyncParameters { { "City", "Toronto" }, { "postal", "M4B 1V5" } };
var s1 = await agent.SynchronizeAsync(setup, parameters);
Console.WriteLine(s1);

parameters = new SyncParameters { { "City", "Montreal" }, { "postal", "H1Y 2H5" } };
s1 = await agent.SynchronizeAsync(setup, parameters);
Console.WriteLine(s1);
```

![image](https://user-images.githubusercontent.com/4592555/188943548-a0e18787-4aa9-45ff-907a-61af67363d0a.png)

**Comment by ricardoamm** [comment]
Strange,

My in the second time returns 0.

![image](https://user-images.githubusercontent.com/26299584/188951607-d0e82c26-4679-4165-83dd-0718d9487342.png)

**Comment by Mimetis** [comment]
Show me the code you are using (for the `AdventureWorks` sample)

**Comment by ricardoamm** [comment]
[Program.cs.txt](https://github.com/Mimetis/Dotmim.Sync/files/9508908/Program.cs.txt)

**Comment by Mimetis** [comment]
Thanks for the feedback

Please use the markdown system (and not an uploaded file) to share your code.
Way better for everyone :)

Seems I've got an error in the prerelease that is already fixed in the master branch
I will publish a new prerelease in the next couple of days

**Comment by Mimetis** [comment]
As a workaround, here is a trick, until next pre release is published:

``` cs
// Creating an agent that will handle all the process
var agent = new SyncAgent(clientProvider, serverProvider);

var parameters = new SyncParameters { { "City", "Toronto" }, { "postal", "M4B 1V5" } };
var s1 = await agent.SynchronizeAsync(setup, parameters);
Console.WriteLine(s1);

parameters = new SyncParameters { { "City", "Montreal" }, { "postal", "H1Y 2H5" } };

// Force create new scopeinfoclient for Montreal
await agent.LocalOrchestrator.GetScopeInfoClientAsync(syncParameters: parameters);

s1 = await agent.SynchronizeAsync(setup, parameters);
Console.WriteLine(s1);

```

**Comment by ricardoamm** [comment]
Hello,

Thank you so much for your help.
I have some projects developed in Microsoft Sync Framework, but the support is discontinued, and it has some limitations.
Your project seems a good alternative, so i intented to use it in a current project.

Best Regards,
Ricardo

**Comment by Actii** [comment]
Hi @Mimetis I'm with @ricardoamm on this project. We built the solution with the hotfix that you gave us and also tried with the the the latest commit from the HandlingErros branch. The problem still persists. I'm going to try to explain what we are doing and what we are trying to achieve.

Everything will be with the database AdventureWorks.
Using the ComplexFilter sample, we do the first sync with the parameters city and postal.

` var parameters = new SyncParameters { { "City", "Toronto" }, { "postal", DBNull.Value } };`

When we sync the databases for the first time we expect to get all Customers from Toronto. And that is what we get. So the first sync is all done and good.

![image](https://user-images.githubusercontent.com/13372586/189086710-5b100156-bffe-4e85-be20-de118dad432c.png)

The problem resides here. If I go to the database and take a Costumer that is not from Toronto:
`330021	0	Mr.	Ben	NULL	Miller` 
This Ben Miller is from the city of Mississauga.
Now I will change this costumer city to Toronto on the Address table and will sync the databases.

What I expect to get is this costumer since I changed its city to Toronto. But that is not what I get after the sync.

![image](https://user-images.githubusercontent.com/13372586/189088596-5382215f-34ba-4b81-a66e-e0d37b255ac1.png)

As you can see I only get 1 update which is the change in address from Mississauga to Toronto. Shouldn't I also get a new record on the table Customer since now Miller is from Toronto?

Thanks for the help.

**Comment by Mimetis** [comment]
Indeed, this is an edge effect.

Since the **Customer** didn't changed (when you've updated its **Address**) the tracking line (in **Customer_tracking** table) is not updated as well, and the customer is not sent back to your client database.

`DMS` is a sync framework, it's just syncing tables whatever are your rules.

If you want the customer to be sent back to your client, if you are changing an address, you need to update the customer as well (a simple UPDATE will do the trick)

``` sql
Update CustomerAddress set Address = 12 where CustomerId = 1
Update Customer Set ModifiedDate = getdate() Where CustomerID = 1
```
You can also create an update trigger on `CustomerAddress` to make this trick automatic
